all:
#  exclude:
#    - 'spec/**/*'
# exclude files for single runner
#eslint:
#  exclude:
#    - 'app/assets/**/*'
github:
  slug: starswan/betgraph
  access_token: B26354
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
rubocop:
  # Map of RuboCop severity level to Pronto severity level
  severities:
    refactor: info
    warning: error
  # Enable suggestions
  suggestions: true
max_warnings: 150
warnings_per_review: 30
verbose: true
runners: [rubocop, undercover] # only listed runners will be executed
skip_runners: [reek] # all, except listed runners will be executed
