#
# $Id$
#
development:
  adapter: mysql2
  encoding: utf8
  database: bfrails_development
  username: rails
  password: 123rails!
  host: localhost
  #  port: 3307
  # using the name rather than the IP address appears to
  # slow everything to a crawl but no idea why.
  #  host: Stephens-iMac.broadband
#  host: 192.168.1.7

# Very simple pg - use local unix user for username
pg:
  adapter: postgresql
  #  encoding: unicode
  #  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: betgraph_development
  username: rails
  password: 123rails!
  host: localhost
  port: 5433

arthur:
  adapter: mysql2
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock
  database: bfrails_development
  username: rails
  password: 123rails!

preprod:
  adapter: mysql2
  encoding: utf8
  database: bfrails_preprod
  username: rails
  password: 123rails!
  reconnect: true
  #  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  port: 3307

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: <%= ENV.fetch("TEST_DB", "mysql2") %>
  encoding: utf8
  pool: 5
  #  adapter: postgresql
  #  encoding: unicode
  #  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: bfrails_test
  username: rails
  password: 123rails!
  host: "127.0.0.1"
#  port: 3307

production:
  adapter: mysql2
  encoding: utf8
  database: ssarbicity
  username: starswan
  password: <%= ENV['MYSQL_STARSWAN_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

pi:
  adapter: mysql2
  encoding: utf8
  database: bfrails_development
  username: rails
  password: 123rails!
  host: arthur

ford:
  adapter: mysql2
  encoding: utf8
  database: bfrails_development
  username: rails
  password: 123rails!
  socket: /var/run/mysqld/mysqld.sock
