#
# $Id$
#
webservice: localhost:3015
sitesurl: sites.starswan.com
dirdepth: 3
makeMarketsInterval: 375
# 5 minute cache timeout
allMarketsCacheTimeout: 300
keyfile: ~/betgraph/shared/client-2048.key
certfile: ~/betgraph/shared/client-2048.pem
