#
# $Id$
#
webservice: betgraph.starswan.com
sitesurl: sites.starswan.com
dirdepth: 3
makeMarketsInterval: 600
allMarketsCacheTimeout: 600
keyfile: ~/html/betgraph/shared/client-2048.key
certfile: ~/html/betgraph/shared/client-2048.pem
