name: Ruby

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']
    services:
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: 123rails!
          POSTGRES_DATABASE: betgraph_test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    env:
      RAILS_ENV: test
      RAPID_API_KEY: test

    steps:
      - name: Checkout whole repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up CMake for undercover gem
        uses: lukka/get-cmake@latest

      - name: Update to latest
        run: sudo apt update

      - name: Install libcurl for 'curb' gem
        run: sudo apt install libcurl4-openssl-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Rubocop
        run: bundle exec rubocop

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run CSS and JS Pipeline
        run: bundle exec rake spec:prepare

      - name: Setup log directory
        run: mkdir -p log

      - name: Setup test db
        run: bundle exec rake parallel:setup

      # Run ruby tests in headless mode
      # Run ruby tests in headless mode
      - name: Ruby tests
        run: xvfb-run -a bundle exec rake parallel:spec
        env:
          COVERAGE: 0