name: Ruby

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
#        some issue with zipfiles on ruby 3.3
#        ruby-version: ['3.1', '3.2', '3.3']
        ruby-version: ['3.1', '3.2']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: bfrails_test
          MYSQL_USER: rails
          MYSQL_PASSWORD: 123rails!
          MYSQL_ROOT_PASSWORD: toor
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      RAILS_ENV: test
      RAPID_API_KEY: test

    steps:
      - name: Checkout whole repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CMake for undercover gem
        uses: lukka/get-cmake@latest

      - name: Update to latest
        run: sudo apt update

      - name: Install libcurl for 'curb' gem
        run: sudo apt install libcurl4-openssl-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Rubocop
        run: bundle exec rubocop

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Yarn install
        run: yarn install

      - name: Setup log directory
        run: mkdir -p log

      - name: Setup test db
        run: bundle exec rake db:create db:schema:load

      # Run ruby tests in headless mode
      - name: Ruby tests
        run: xvfb-run -a bundle exec rake spec
        env:
          COVERAGE: 0