# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.1', '3.2']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: bfrails_test
          MYSQL_USER: rails
          MYSQL_PASSWORD: 123rails!
          MYSQL_ROOT_PASSWORD: toor
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up CMake
      - uses: lukka/get-cmake@latest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Rubocop
        run: bundle exec rubocop

      - name: Setup test db
        run: bundle exec rake db:create

      - name: load schema
        run: bundle exec rake db:schema:load

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Yarn install
        run: yarn install
      - name: Run Ruby tests
        run: bundle exec rspec -t ~betfair
      - name: Check coverage
        run: bundle exec undercover -c main -l coverage/betgraph.lcov
